# Generated by Django 2.2.2 on 2019-06-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('data', models.DateField(auto_now=True)),
                ('guarnicao', models.CharField(max_length=50)),
                ('hora_fato', models.TimeField()),
                ('hora_comunicacao', models.TimeField()),
                ('hora_local', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('local', models.CharField(max_length=100)),
                ('natureza', models.CharField(max_length=50)),
                ('historico', models.TextField()),
            ],
        ),
    ]
