# Generated by Django 2.2.2 on 2019-06-09 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
