# Generated by Django 2.2.2 on 2019-06-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='viatura',
        ),
    ]
