# Generated by Django 2.2.2 on 2019-06-29 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0003_rdo_viatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='timestamp',
        ),
    ]
