# Generated by Django 2.2.2 on 2019-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0004_remove_rdo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdo',
            name='data',
            field=models.DateField(),
        ),
    ]
