# Generated by Django 2.2.2 on 2019-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0005_auto_20190629_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdo',
            name='timestamp',
            field=models.TextField(default=None),
        ),
    ]
