# Generated by Django 2.2.2 on 2019-06-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novo_rdo', '0006_rdo_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdo',
            name='timestamp',
        ),
    ]
